version: '3'
services:
  rc-app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - rc-network
  rc-redis:
    image: redis
    container_name: rc-redis-container
    ports:
      - "6379:6379"
    networks:
      - rc-network
    volumes:
      - ./src/redis/redis.conf:/usr/local/etc/redis/redis.conf  # Mount custom config file
networks:
  rc-network: